### ISSUE TITLE
523-Crashing From: "Floating-point exception - erroneous arithmetic operation."

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#25]
**Describe the bug**
I ran a parameter sweep using QF523. A handful of simulations crashed throwing the errror below. I thought it would be good make sure QF531 didn't inherit this bug. 

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f64e3fa8171 in ???
#1  0x7f64e3fa7313 in ???
#2  0x7f64e2fdeb7f in ???
#3  0x472c2b in computemagnitudescale_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//FireCA_LDRD.F90:350
#4  0x4667b4 in firepropagationcreeping_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//FireCA_common_subs.F90:3433
#5  0x467406 in loopoverignitions_._omp_fn.26
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//FireCA_common_subs.F90:300
#6  0x7f64e39e0725 in ???
#7  0x465b16 in loopoverignitions_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//FireCA_common_subs.F90:384
#8  0x469b9f in computenewfirespread_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//FireCA_common_subs.F90:158
#9  0x46f066 in updatefire_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//FireCA_common_subs.F90:3004
#10  0x4b1fc9 in dofireiter_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//main.F90:203
#11  0x4b23ab in dowindtimeiteration_
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//main.F90:96
#12  0x4b2434 in MAIN__
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//main.F90:50
#13  0x4b2554 in main
	at /mnt/beegfs/data/zcope/QF_ver/QF_5.2.3/src/quic_fire//main.F90:17

**To Reproduce**
https://drive.google.com/drive/folders/13iXRoLmYMw36E3KvQh6hSWICnfImEJT5?usp=drive_link

**Desktop (please complete the following information):**
 - QF Version: QFVD5.2.3
 - OS: Linux

**Comment by zacharycope0** [comment]
@drobinson6045 I got another "SIGFPE: Floating-point exception - erroneous arithmetic operation" error. This simulation was running on multiple threads so I don't think it will be easy to recreate:

![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/07953ef5-a829-40cc-8ead-c0558eaf5a3f)

**Comment by zacharycope0** [comment]
@drobinson6045. Here is where I put the issue.
